### ISSUE TITLE
Unable to add repl_definition

### ISSUE THREAD

**Issue by c0ppelius** [hkupty/iron.nvim#244]
Perhaps this is user error but I am unable to set any new filetypes. 

Here is my configuration
```lua
require('iron.core').setup{
  config = {
    repl_definition = {
      Macaulay2 = {
	      command = {"M2"},
      }
    }
  }
}
```

The error returned 
```
Error executing Lua callback: There's no REPL definition for current filetype Macaulay2
stack traceback:
        [C]: in function 'error'
        ...m/site/pack/packer/start/iron.nvim/lua/iron/lowlevel.lua:40: in function 'get_ft'
        .../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:389: in function <.../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:388>
```

I have also tried it with Matlab from #236 and received the same error. 

Any help would be appreciated. Thanks.

**Comment by hkupty** [comment]
Hi @c0ppelius,

I've recently merged a pull-request that might've solved this issue, #242.
Of course, it can be that the bug still exists and I need to look thoroughly. Would you mind updating iron just to be sure it is not the same issue that was fixed today?

**Comment by c0ppelius** [comment]
I have the new version with `get_ft` in core.

**Comment by c0ppelius** [comment]
I have the new version with `get_ft` in core.

**Comment by hkupty** [comment]
Got it, thanks for confirming.

**Comment by hkupty** [comment]
Ok, I managed to reproduce it locally.

**Comment by hkupty** [comment]
I'm assuming the fix I just merged should to the trick. Let me know how it goes.

**Comment by c0ppelius** [comment]
It is still throwing the same error but now is reporting the line number with the callback.
```
Error executing Lua callback: ...m/site/pack/packer/start/iron.nvim/lua/iron/lowlevel.lua:40: There's no REPL definition for current filetype Macaulay2
stack traceback:
        [C]: in function 'error'
        ...m/site/pack/packer/start/iron.nvim/lua/iron/lowlevel.lua:40: in function 'get_ft'
        .../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:389: in function <.../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:388>
```

**Comment by c0ppelius** [comment]
It is still throwing the same error but now is reporting the line number with the callback.
```
Error executing Lua callback: ...m/site/pack/packer/start/iron.nvim/lua/iron/lowlevel.lua:40: There's no REPL definition for current filetype Macaulay2
stack traceback:
        [C]: in function 'error'
        ...m/site/pack/packer/start/iron.nvim/lua/iron/lowlevel.lua:40: in function 'get_ft'
        .../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:389: in function <.../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:388>
```

**Comment by c0ppelius** [comment]
I created blank `test.jl` and `test.cjl` files and called `:IronRepl`. I got the same error (except for different filetype).

**Comment by c0ppelius** [comment]
I created blank `test.jl` and `test.cjl` files and called `:IronRepl`. I got the same error (except for different filetype).

**Comment by hkupty** [comment]
Got it. Found the issue.

**Comment by hkupty** [comment]
Should be fixed (hopefully) now :)

**Comment by c0ppelius** [comment]
It is! Thank you!

**Comment by c0ppelius** [comment]
It is! Thank you!
