### ISSUE TITLE
E5108: end_col value outside range when sending wrapped line to REPL

### ISSUE THREAD

**Issue by jolars** [hkupty/iron.nvim#269]
If I decrease the width of a line in a buffer so that it gets wrapped, I receive the following error upon trying to send it (the line) to the REPL:

```
E5108: Error executing lua: ...nvim/site/pack/packer/start/iron.nvim/lua/iron/marks.lua:39: end_col value outside range
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        ...nvim/site/pack/packer/start/iron.nvim/lua/iron/marks.lua:39: in function 'set'
        .../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:214: in function <.../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:207>
```
This happens regardless of whether I do a visual send or a send motion. This also happens if I select several lines and the last of them is wrapped. Sending a block with a wrapped line works fine as long as it's not the last line in the block.

**Comment by hkupty** [comment]
Hi, sorry for the long time to answer, I've been absent for some time due to summer vacations.

I think this might've been fixed by #272. Would you mind checking it out?

Best regards,
Henry

**Comment by jolars** [comment]
No worries, thanks for responding. The fix unfortunately doesn't solve my problem.

**Comment by cands** [comment]
I also experience this bug, which is a bit annoying. If wrapping is turned off in Vim `:setlocal nowrap` it works as expected, but when lines are wrapped the problem occurs as described by @jolars

**Comment by jakubkaczor** [comment]
I get the same error when the text object is larger, than the part of buffer that is visible. For example, in Markdown, when I use ``i`<CR>`` (inner backticks) in order to send the code block content, where `<CR>` is mapped to the appropriate send command, it raises an error when the code spans more the visible portion of the buffer. But when I first select it with `` vi` `` and then send, it works as expected.

**Comment by brianfabre** [comment]
Has there been any update yet? I have also noticed that i get this error when any line sent is wrapped. The only way to fix it is to 'set wrap' but that would not be very ideal.
